// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsOoxXaaAQZv2jLGktvTppc356dATrqAg',
    appId: '1:706108783108:web:c6df6f683c722e57fa5351',
    messagingSenderId: '706108783108',
    projectId: 'aplikasi-aduan-61031',
    authDomain: 'aplikasi-aduan-61031.firebaseapp.com',
    storageBucket: 'aplikasi-aduan-61031.firebasestorage.app',
    measurementId: 'G-5VW1EFGKX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACQzKp4vbP74fEhk30_ExjCHroTyU4maM',
    appId: '1:706108783108:android:ace627007cad4401fa5351',
    messagingSenderId: '706108783108',
    projectId: 'aplikasi-aduan-61031',
    storageBucket: 'aplikasi-aduan-61031.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6nLMD_P-rTWU88U-ZIRLAZnMWdycayMA',
    appId: '1:706108783108:ios:7959e57e3ea0b329fa5351',
    messagingSenderId: '706108783108',
    projectId: 'aplikasi-aduan-61031',
    storageBucket: 'aplikasi-aduan-61031.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiAduan',
  );
}
